### PR TITLE
 basic video and image rendering complete

### PR DESCRIPTION
**Pull request by Happypals**
LOL, finally did some work this week, yah!

### CODE REVIEW

**Review by dyliman — APPROVED** [review]
looks fine. you should make it so that when you make a pull request to master, an approving review is required before you can merge.

**Comment by Happypals** [comment]
I see. I was just changing the directory of those data to another file. I
will definitely wait for a review next time!

**Comment by dyliman** [comment]
Oh thats fine, what i meant is that in your repo, you should go to settings -> branch -> master and enable the 'protect this branch' option

**Comment by dyliman** [comment]
because right now, even without an approving review, you can still merge

**Comment by Happypals** [comment]
I gotcha.

**Pull request merged**
